[versions]
detekt = "1.23.8"
kotlin = "2.3.0"
ktlintGradle = "12.1.1"
pluginPublish = "1.3.1"
versionCheck = "0.53.0"
android-lint = "8.6.0"
android-lint-gradle = "1.0.0-alpha05"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle"}
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck"}
lint = { id = "com.android.lint", version.ref = "android-lint"}

[libraries]
junit = "junit:junit:4.13.2"
android-lint-gradle = { module = "androidx.lint:lint-gradle", version.ref = "android-lint-gradle" }